#!/usr/bin/env sh
set -e

export CR_NGINX_PASS_SERVER="${CR_NGINX_PASS_SERVER:-127.0.0.1}"
export CR_NGINX_PASS_PORT="${CR_NGINX_PASS_PORT:-8000}"

# eg. EO-Connecting-IP CF-Connecting-IP
RAW_HEADER="${CR_NGINX_REAL_IP:-X-Forwarded-For}"
FORMATTED_HEADER=$(echo "$RAW_HEADER" | tr '[:upper:]-' '[:lower:]_')
export CR_NGINX_REAL_IP="\$http_${FORMATTED_HEADER}"

envsubst < /etc/nginx/templates/proxy.tmpl > /tmp/nginx/conf.d/proxy.conf